name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  frontend_testing:
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend dependencies
        run: npm run install:frontend
      - name: Lint frontend code
        run: npm run lint:frontend
  backend_testing:
    runs-on: ubuntu-20.04
    environment: test
    env:
      PORT: ${{ vars.PORT }}
      SECRET: ${{ secrets.SECRET }}
      TEST_MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: npm run install:backend
      - name: Lint backend code
        run: npm run lint:backend
      - name: Test backend code
        run: npm run test:backend
  render_deployment:
    needs: [frontend_testing, backend_testing]
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: Trigger Render deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      # - name: Notify on failure
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: ${{ failure() }}
      #   with:
      #     text: Build failed
      #     description: commit ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build :(
      #     severity: error
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [render_deployment]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
          DRY_RUN: false
      # - name: Notify on success
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: ${{ success() }}
      #   with:
      #     text: A new version of Blog deployed
      #     description: to https://blog-5a8n.onrender.com by ${{ github.actor }}
      #     severity: info
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
